# Dependencies
markdown: redcarpet

redcarpet:
  extensions: [
  "no_intra_emphasis",
  "fenced_code_blocks",
  "autolink",
  "strikethrough",
  "superscript",
  "footnotes"
  ]
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo

# Setup
title: Blog do Milhouse
tagline: engenharia, dev e emacs.
url: http://rranelli.com
paginate: 5
baseurl: /
exclude: ["*.org"]
permalink: pretty

author:
  name: Renan Ranelli
  url: https://github.com/rranelli
  email: (concat "rranelli" "@" "gmail")

  #Custom vars
  version: 1.0.0
  github:
    repo: https://github.com/rranelli/rranelli.github.io

page_list:  {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
