# Dependencies
markdown: kramdown

kramdown:
  extensions:
   - no_intra_emphasis
   - fenced_code_blocks
   - autolink
   - strikethrough
   - superscript
   - footnotes
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo

# Setup
title: Milhouse
tagline: on software, engineering, and Emacs.
url: milhouseonsoftware.com
paginate: 7
baseurl: /
exclude: ["*.org"]
permalink: pretty

excerpt_separator: '<p hidden> <span class="underline">excerpt-separator</span> </p>'

author:
  name: Renan Ranelli
  url: https://github.com/rranelli

  github:
    repo: https://github.com/rranelli/rranelli.github.io

page_list:  { 'About':'/about',
              'Archive':'/archive',
              'CV':'/cv/en.pdf',
              'Feed':'/atom.xml'
            }

footer-links:
  github: rranelli
  twitter: renanranelli

plugins:
  - jekyll-paginate
