# Dependencies
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

highlighter: true

input: GFM

# Permalinks
permalink: pretty

# Setup
title: Blog do Milhouse
tagline: engenharia, dev e emacs.
url: http://rranelli.github.io
paginate: 5
baseurl: /
author:
  name: Renan Ranelli
  url: https://twitter.com/rranelli
  email: (concat "rranelli" "@" "gmail")

  #Custom vars
  version: 1.0.0
  github:
    repo: https://github.com/rranelli/rranelli.github.io
