#+OPTIONS: -*- eval: (org-jekyll-mode) -*-
#+AUTHOR: Renan Ranelli (renanranelli@gmail.com)
#+OPTIONS: toc:nil n:3
#+STARTUP: showall indent
#+STARTUP: oddeven
#+STARTUP: hidestars
#+BEGIN_HTML
---
language: brasileiro
layout: post
title: Keysnail
---
#+END_HTML

  <p hidden> _excerpt-separator_ </p>

Já a um tempo não estava satisfeito com os atalhos para navegação no
google-chrome, principalmente agora que estou bastante acostumado com o estilo
de =keybindings= do Emacs. O que eu queria era uma forma de "Emaczificar" a
experiência de navegação. Em suma, eliminar completamente o teclado da navegação
web.

Procurei bastante a respeito de como customizar os atalhos do google-chrome, mas
não achei nada útil. Encontrei o [[https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en][vimium]] que ajudou um pouco, mas estava longe de
ser ideal. Encontrei um tal de [[http://www.vimperator.org/][Vimperator]] que parecia ser exatamente o que eu
queria, só que para usuários de vim.

Já tinha desistido quando acabei descobrindo (por acaso) no Github o [[https://github.com/mooz/keysnail/wiki][Keysnail]]. O
Keysnail era _exatamente_ o que eu estava procurando! O único problema é que ele
não existe para google-chrome, apenas para firefox. Não pensei duas vezes e
migrei completamente para o firefox.

Existem 4 "modes" nele: =global=, =view=, =edit= e =caret=. É possível definir
=keybindings= para qualquer função =javascript= definida no seu arquivo
=.keysnail.js= e, é claro, os =keybindings= são sujeitos ao escopo dos =modes=.

A arquitetura do Keysnail é bem bacana, e existem vários plugins pra ele. De
fato, é um plugin que incorpora o espirito do Emacs.
