#+OPTIONS: -*- eval: (org-jekyll-mode) -*-
#+AUTHOR: Renan Ranelli (renanranelli@gmail.com)
#+OPTIONS: toc:nil n:3
#+STARTUP: showall indent
#+STARTUP: oddeven
#+STARTUP: hidestars
#+BEGIN_HTML
---
language: brasileiro
layout: post
comments: true
title: Primeiro Post
---
#+END_HTML

  _<p hidden>excerpt-separator<p hidden>_

Esse é o primeiro post do meu primeiro blog. Depois de passar um bom tempo sem
escrever nada na vida, resolvi me organizar para dividir conteúdo interessante e
pensamentos.

Tenho várias ideias para escrever sobre a relação entre engenharia de software e
engenharia industrial. Acredito que o meu caminho para vir parar no mundo do
software é bem diferente da maioria das pessoas (mais sobre isso no futuro) e é
possível que eu tenha algo interessante para compartilhar. O impeto pra isso
surgiu ao ler uns dos capítulos finais do [[http://www.amazon.com/The-Mythical-Man-Month-Engineering-Anniversary/dp/0201835959]["The mythical man month"]] onde o autor
exemplifica o paralelo entre uma planta piloto e o desenvolvimento iterativo de
software.

Também quero apresentar conteúdo sobre Emacs, já que é bem difícil encontrar
informações sobre o editor editável em português. Bastante gente julga o editor
"impossível de aprender". Vou tentar gastar um pouco de teclado explicando como
na realidade a maior parte das coisas é simples uma vez que você aprende como
"descobrir" as funcionalidades do editor.

Este blog é escrito usando o [[http://www.gnu.org/software/emacs/][Emacs]], [[http://jekyllrb.com/][Jekyll]] e [[https://github.com/poole/poole][Poole]]. O =gfm-mode= é bem bacana
também. Seria bem bacana escrever o texto com o =org-mode= por cause do suporte
_fantástico_ a código fonte, mas exportar =.org= para =.md= não me pareceu tão
fácil.
