#+OPTIONS: -*- eval: (org-jekyll-mode) -*-
#+AUTHOR: Renan Ranelli (renanranelli@gmail.com)
#+OPTIONS: toc:nil n:3
#+STARTUP: showall indent
#+STARTUP: oddeven
#+STARTUP: hidestars
#+BEGIN_HTML
---
language: english
layout: default
title: About
---
#+END_HTML

My name is Renan Ranelli. I'm a {chemical,software} engineer, Emacs aficionado,
sometimes gamer and permanently nerd.

In this space I will talk about software development and its contrast with
industrial engineering projects (which I had the {dis,}pleasure of working for
two and a half years after graduating). I also talk about the stuff I'm
studying, the stuff I code in Emacs and other brain dumps.

I'm currently working at [[http://www.locaweb.com.br][Locaweb]] as a software engineer. I work full-time with
Ruby. I also know Java, Lisp (Clojure and Scheme), Javascript, a little bit of
Scala, F#, Haskell and a bunch of C#. I Never touched PHP, did almost no
front-end workand. Probably the next thing for is learning Rust or Elixir.

During college I worked with /advanced process control/ in a research group.
There I had the opportunity to program in widely different environments, from
machine programming (Ladder, grafcet, C) to solving high level simulation and
optimization problems with non-trivial mathematical methods in {Mat,Sci}lab and
Octave. I even had to code some of my code in Fortran for raw speed on
number-crunching.

I'm an voracious reader. I keep up with my reading using [[http://goodreads.com][goodreads]]. Here is my
[[https://www.goodreads.com/user/show/19870807-renan-ranelli][profile]] there.

If you're interested can get my CV [[cv/cv.pdf][here]] (still in Portuguese only, probably
gonna translate it in the nar future).
