#+OPTIONS: -*- eval: (org-jekyll-mode) -*-
#+AUTHOR: Renan Ranelli (renanranelli@gmail.com)
#+OPTIONS: toc:nil n:3
#+STARTUP: showall indent
#+STARTUP: oddeven
#+STARTUP: hidestars
#+BEGIN_HTML
---
language: english
layout: default
title: About
---
#+END_HTML

My name is Renan Ranelli. I'm a {chemical,software} engineer, Emacs aficionado,
sometimes gamer and permanently nerd.

In this space I will talk about software development and its contrast with
industrial engineering projects (which I had the {dis,}pleasure of working for
two and a half years after graduating). I also talk about the stuff I'm
studying, the stuff I code in Emacs and other brain dumps.

I'm currently working full-time with Ruby at [[http://www.locaweb.com.br][Locaweb]] as a software engineer. I
also know Java, Lisp (Clojure and Emacs lisp), Javascript, a little of Scala,
F#, Haskell and a bunch of C#. I Never touched PHP, and did almost no front-end
work. I'm currently learning [[http://elixir-lang.org/][Elixir]] and I'm loving it!

During college I worked with /advanced process control/ in a research group.
There I had the opportunity to program in widely different environments, from
machine programming (Ladder, grafcet, C) to solving high level simulation and
optimization problems with non-trivial mathematical methods in {Mat,Sci}lab and
Octave. I even had to code some of my code in Fortran for raw speed on
number-crunching.

I'm a voracious reader. I keep up with my reading using [[http://goodreads.com][goodreads]]. Here is my
[[https://www.goodreads.com/user/show/19870807-renan-ranelli][profile]] there. My goal this year is to read 16 technical books.

If you're interested can get my CV [[cv/en.pdf][here]]. (a version in [[cv/pt.pdf][portuguese]] is also
available)
