#+OPTIONS: -*- eval: (org-jekyll-mode); eval: (writegood-mode) -*-
#+AUTHOR: Renan Ranelli (renanranelli@gmail.com)
#+OPTIONS: toc:nil n:3
#+STARTUP: oddeven
#+STARTUP: hidestars
#+BEGIN_HTML
---
language: english
layout: post
comments: true
title: 'The Duality Between Object Oriented And Functional Programming'
---
#+END_HTML

* <p hidden>The Duality Between Object Oriented And Functional Programming<p hidden>

  *TL;DR*:

  _<p hidden>excerpt-separator<p hidden>_

  [FIXME: Introduce stuff by talking about your talk and how you spoke with
  someone afterwards and suggested that he would look for other ways of looking
  at software so that he would finally understand OOP. Also, suggest people to
  go look at the fabulous programming languages course by dan grossman.]

  [FIXME: Talk about the principles of OOP:
  http://userpage.fu-berlin.de/~ram/pub/pub_jf47ht81Ht/doc_kay_oop_en]

  [FIXME: talk about the separation between accidental complexity and
  fundamental complexity when designing systems in OOP. [[[http://en.wikipedia.org/wiki/No_Silver_Bullet][fred brooks no silver
  bullet essay]]] Emphasize how you should think about OBJECTS and MESSAGES when
  designing the system, and go to details of classes and composition AFTER that.
  Say that classes and other things like that are accidental in the sense of
  object oriented design. By working only with the root elements and most
  fundamental concepts you don't cloud your judgment when working with systems
  and shit.]

  [FIXME: When talking about the duality between OOP and Fp, we should
  definetely cite the essay [[http://steve-yegge.blogspot.com.br/2006/03/execution-in-kingdom-of-nouns.html]["EXECUTION IN THE KINGDOM OF NOUNS"]]. The thing we
  extract from there is that the OOP tradition "nounficates" the verbs. With
  that, what you *actually* want is a FUNCTION. Talk about how patterns like the
  strategy pattern are actually just workarounds the fact that your language
  lacks higher order functions]

  [FIXME: Also, [[%20%20%20%20%20%20http://c2.com/cgi/wiki?ClosuresAndObjectsAreEquivalent][closure and objects are equivalent]]. A closure is behavior with
  data attached, and an object is data with behavior attached.]


  /rest of the content/

  That's it.

  ---

  /footnotes come here/ (1)
